language: python
python:
  - 2.7
  - 3.3
install:
  - pip install -e .
  - pip install -r requirements.txt --use-mirrors
script: ./manage.py test --failfast
env:
  - DJANGO_SETTINGS_MODULE="lingvista.settings.test"